### ISSUE TITLE
Update to 1.19.3

### ISSUE THREAD

**Issue by ChacePratt** [CafeteriaGuild/fake-player-api#7]
Whenever a new fake server player is made in 1.19.3, MC crashes. 

java.lang.NoSuchMethodError: 'void net.minecraft.class_3222.<init>(net.minecraft.server.MinecraftServer, net.minecraft.class_3218, com.mojang.authlib.GameProfile, net.minecraft.class_7428)'
	at dev.cafeteria.fakeplayerapi.server.FakeServerPlayer.<init>(FakeServerPlayer.java:17)

It seems 1.19.3 changed the name or parameters of a method your API relies on.
I believe all that needs to be done to fix this one error is to remove the null variable on line 17 of FakeServerPlayer.java, so hopefully that would be an easy fix.

protected FakeServerPlayer(FakePlayerBuilder builder, MinecraftServer server, ServerWorld world, GameProfile profile) {
        super(server, world, profile, null);
        [...]
}

to this:

protected FakeServerPlayer(FakePlayerBuilder builder, MinecraftServer server, ServerWorld world, GameProfile profile) {
        super(server, world, profile);
        [...]
}

---
Have a good day!
Gitko

**Comment by TelepathicGrunt** [comment]
Happening for me in 1.19.4 as my mod relies on FakePlayerApi
https://github.com/TelepathicGrunt/Bumblezone/issues/234

**Comment by TelepathicGrunt** [comment]
0.6.0 Fake Player Lib released now fixes the crash in 1.19.4. This can be closed now

**Comment by ChacePratt** [comment]
I think the way I'm handling setting up my fake player is wrong because I still get an error. However, it is a different error.
https://pastebin.com/J6H97DYH

**Comment by TelepathicGrunt** [comment]
You're still on 1.19.3. Update to 1.19.4 and the new Fake Player API will work. 1.19.4 basically killed off 1.19.3 so there's really not much reason to stick with 1.19.3 as even modpacks are sticking with 1.19.2 as well. Either people stick with 1.19.2 for modpacks or go to 1.19.4 for latest

**Comment by ChacePratt** [comment]
Good idea, saves me some work! 
1.19.4 works great
